### ISSUE TITLE
InvalidOperationException throw in HeaderMultiValueAssertion

### ISSUE THREAD

**Issue by kvpt** [JasperFx/alba#128]
Hi,

Following the update to Alba 7.2.0 I have some tests that fail with an InvalidOperationException.

My test has this form

```cs
[Fact]
public async Task ShouldGetLastVersion()
{
    await Api.Scenario(s =>
    {
        s.Head
            .Url("version/last");

        s.StatusCodeShouldBe(HttpStatusCode.OK);

        s.Header(HeaderNames.ETag).ShouldHaveValues();
    });
}
```

The issue seems to be in the HeaderMultiValueAssertion, the excepted is empty and cause the aggregate to throw.
![image](https://user-images.githubusercontent.com/1446221/204847296-e12dbc86-7f53-4497-b254-e901c5232d6c.png)

**Comment by Hawxy** [comment]
Hey, thanks for reporting this. `ShouldHaveValues()` was actually never intentionally designed to work with no values passed in, so the fact this worked to begin with was a happy accident. I've added a new overload for this scenario that uses a different assertion in v7.2.1.
