### ISSUE TITLE
Target .NETFramework 4.5.1

### ISSUE THREAD

**Issue by DixonDs** [JasperFx/alba#37]
Is it possible to target .NETFramework 4.5.1 as well? It looks like all dependencies are targeting it, so it shouldn't be a problem

**Comment by jeremydmiller** [comment]
I was honestly just waiting for someone to ask for that;) I'd happily take a PR for that.

**Comment by jeremydmiller** [comment]
Yeah man, sorry, that's not gonna happen. The latest Lamar is on ASP.Net Core 2.1 and that means netcoreapp2.1/netstandard2.0
