### ISSUE TITLE
docs(assertions): misprint above first sample

### ISSUE THREAD

**Issue by GiuseppePiscopo** [JasperFx/alba#44]
Looking at this doc page: http://jasperfx.github.io/alba/documentation/assertions/ above the first code sample it says:

> As an example, here's the assertion from Alba that validates that the response body is supposed to

which seems truncated or somehow misprinted. 

Sorry for not submitting a PR for https://github.com/JasperFx/alba/blob/master/documentation/documentation/assertions.md, don't know how you wanted to reword it. HTH

**Comment by Hawxy** [comment]
Closing due to issue age, docs were rebuilt for v5 so this shouldn't be a problem anymore :)
