### ISSUE TITLE
.NET core 2.1 support

### ISSUE THREAD

**Issue by esterad** [JasperFx/alba#50]
Is support for .NET core 2.1 planned? 

I just wonder whether I have to rewrite my integration tests using Microsoft.AspNetCore.Mvc.Testing.

PS
I took a crack at debugging but it exceeded my skills. I fear that changes in .net core 2,1 are too great to easily migrate Alba.

**Comment by jeremydmiller** [comment]
@esterad Sorry for the slow response, you caught me on vacation. I don't think this is gonna be all that big of a deal to address. I already his some of this with Jasper when I moved that up to 2.1. I'll try to get this fixed by Tuesday.

**Comment by esterad** [comment]
@jeremydmiller  Looking forward  to this fix :) Hope it would go smoothly. Thank you for creating and supporting Alba - great piece of software

**Comment by jeremydmiller** [comment]
Meh, by this coming Monday. Haven't forgotten you, just backed up

**Comment by jeremydmiller** [comment]
@esterad Would you try out Alba.AspNetCore2 v1.4.1 and see if it addressed your issues? I was able to verify it worked against what I was doing in an ASP.Net Core app using 2.1. If it does manage to fix things, it was just a 1 line code fix.

**Comment by esterad** [comment]
It works! Thank you 👍
