### ISSUE TITLE
Fill in service registration for HttpContextAccessor

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/alba#53]
Or throw a descriptive exception if it doesn't exist. Alba has to have it, so get it there

**Comment by joemcbride** [comment]
Currently being added here. 
 https://github.com/JasperFx/alba/blob/master/src/Alba/SystemUnderTest.cs#L121

**Comment by jeremydmiller** [comment]
Yeah, but that doesn't get called if you build the WebHost directly by overriding that method:(

**Comment by jeremydmiller** [comment]
Meh, really handled this by ignoring it if the HttpContextAccessor isn't there.
