### ISSUE TITLE
ISystemUnderTest.Services throws Exception in Alba v4

### ISSUE THREAD

**Issue by mronnblom-cint** [JasperFx/alba#81]
When using Alba v4 with newer versions of AspNetCore which uses `IHost` instead of `IWebHost`, accessing `IServiceProvider` via the explicit `ISystemUnderTest.Services` throws the Exception:
`The TestServer constructor was not called with a IWebHostBuilder so IWebHost is not available.`

From what I can tell, this is because it calls:
`IServiceProvider ISystemUnderTest.Services => Server.Host.Services;`

When it should call:
`IServiceProvider ISystemUnderTest.Services => _host.Services;`

I don't know enough about the inner workings of the Generic Host and TestServer to understand why, but you have apparently changed the ctor (taking `IHostBuilder`) to do that already.

Here is a unit test that demonstrates the three ways to use the `IServiceProvider`, with the third one failing:
```
[Fact]
public void MyTest()
{
	// OK
	var foo1 = MySUT.Services.GetRequiredService<IHttpContextAccessor>();

	// OK
	var foo2 = MySUT.Server.Services.GetRequiredService<IHttpContextAccessor>();

	// Fail
	var foo3 = ((ISystemUnderTest)MySUT).Services.GetRequiredService<IHttpContextAccessor>(); 
}
```

**Comment by Hawxy** [comment]
Thanks for reporting. Looking at the code I'm actually unsure why `Services` has an explicit interface implementation. This might be a leftover piece of legacy pre-generic host. I've opened a PR to remove it.
