### ISSUE TITLE
Use of System.Text.Json

### ISSUE THREAD

**Issue by schmallaria** [JasperFx/alba#84]
Is there a possibility to use System.Text.Json instead of Json.NET?

**Comment by jeremydmiller** [comment]
In Alba 5, yes.

**Comment by jeremydmiller** [comment]
@satishviswanathan Alba is using the Json serializer from your actual application, so however you have things configured in the app itself, that's what Alba is doing too.

**Comment by satishviswanathan** [comment]
Got it. Thank you @jeremydmiller  for your quick response.
